LangString addOrReinstall ${LANG_CZECH} "Přidat / přeinstalovat součásti"
LangString alreadyInstalled ${LANG_CZECH} "Již nainstalováno"
LangString alreadyInstalledLong ${LANG_CZECH} "${PRODUCTNAME} ${VERSION} je již nainstalován. Vyberte, co chcete provést, a pokračujte tlačítkem Další."
LangString appRunning ${LANG_CZECH} "{{product_name}} je spuštěn! Nejprve ho zavřete a zkuste to znovu."
LangString appRunningOkKill ${LANG_CZECH} "{{product_name}} je spuštěn!$\nKlepnutím na OK ho ukončíte."
LangString chooseMaintenanceOption ${LANG_CZECH} "Vyberte, jakou údržbu chcete provést."
LangString choowHowToInstall ${LANG_CZECH} "Vyberte, jak chcete ${PRODUCTNAME} nainstalovat."
LangString createDesktop ${LANG_CZECH} "Vytvořit zástupce na ploše"
LangString dontUninstall ${LANG_CZECH} "Neodinstalovávat"
LangString dontUninstallDowngrade ${LANG_CZECH} "Neodinstalovávat (instalace starší verze bez odinstalace je u tohoto instalátoru zakázána)"
LangString failedToKillApp ${LANG_CZECH} "{{product_name}} se nepodařilo ukončit. Nejprve ho zavřete a zkuste to znovu."
LangString installingWebview2 ${LANG_CZECH} "Instaluje se WebView2…"
LangString newerVersionInstalled ${LANG_CZECH} "Je již nainstalována novější verze ${PRODUCTNAME}! Instalace starší verze se nedoporučuje. Pokud ji opravdu chcete nainstalovat, nejprve raději odinstalujte tu současnou. Vyberte, co chcete provést, a pokračujte tlačítkem Další."
LangString older ${LANG_CZECH} "starší"
LangString olderOrUnknownVersionInstalled ${LANG_CZECH} "V systému je nainstalována $R4 verze ${PRODUCTNAME}. Před instalací doporučujeme současnou verzi odinstalovat. Vyberte, co chcete provést, a pokračujte tlačítkem Další."
LangString silentDowngrades ${LANG_CZECH} "Instalace starší verze je u tohoto instalátoru zakázána, tichá instalace nemůže pokračovat. Použijte prosím instalátor s grafickým rozhraním.$\n"
LangString unableToUninstall ${LANG_CZECH} "Odinstalace se nezdařila!"
LangString uninstallApp ${LANG_CZECH} "Odinstalovat ${PRODUCTNAME}"
LangString uninstallBeforeInstalling ${LANG_CZECH} "Před instalací odinstalovat"
LangString unknown ${LANG_CZECH} "neznámá"
LangString webview2AbortError ${LANG_CZECH} "WebView2 se nepodařilo nainstalovat! Aplikace bez něj nepoběží. Zkuste instalátor spustit znovu."
LangString webview2DownloadError ${LANG_CZECH} "Chyba: stažení WebView2 se nezdařilo – $0"
LangString webview2DownloadSuccess ${LANG_CZECH} "Instalátor WebView2 byl úspěšně stažen"
LangString webview2Downloading ${LANG_CZECH} "Stahuje se instalátor WebView2…"
LangString webview2InstallError ${LANG_CZECH} "Chyba: instalace WebView2 skončila s kódem $1"
LangString webview2InstallSuccess ${LANG_CZECH} "WebView2 byl úspěšně nainstalován"
LangString deleteAppData ${LANG_CZECH} "Smazat data aplikace"
